### ISSUE TITLE
/addevent command

### ISSUE THREAD

**Issue by RoonMoonlight** [kabiiQ/FBK#8]
**Feature details**
I want to suggest new command for YouTube, `/addevent`. Usually, you cannot add stream waiting room/stream to Discord events unless you explicitly track specific YouTube channel and enable Discord event feature with `/streamcfg` command. However with the `/addevent` command, you can add any streams, premiere videos and waiting rooms for YouTube into Discord event section regardless of specific channel being tracked or not. This feature might be useful for some important event that are not tracked right now and you don't want to manually track specific YouTube channel and manually set up everything for it.

For example, if you type `/addevent link:https://www.youtube.com/live/O_sGeVlKwrU` then it will add [this stream](https://www.youtube.com/live/O_sGeVlKwrU) to Discord event section, like how does the tracked YT channel's discord event system works.

However if you try to add same streams/waiting rooms/premieres or non-stream(e.g. Videos/Privated archives), it will display error message instead.

**Additional context**
None.

**Comment by kabiiQ** [comment]
I see why you would want this feature, but I do not plan on making the events feature separate from the stream tracker even like this. It is an extra feature where the normal stream notifications are still meant to be used. 

That said, if you have a Discord channel with the events feature enabled, individual videos added with `/trackvid` in that channel do get events created (eventually, the next time the stream is processed) so you can mostly achieve this already.
